[pytest]
markers =
    info: marks tests for information consistencies feedback
    hhc-n818op: marks tests for Server HHC-N818OP standalone
    plugins: marks tests for Plugins devices
;addopts = -n auto
