# Standard Library

DEVICE_UNKNOWN = "UNKNOWN"
PLUGIN_MODULE = "plugin_module"
PLUGIN_CLASS = "plugin_classname"
MQTT = "mqtt"
MILLISECONDS = "milliseconds"
TIME = "time"
DATE = "date"
NAME = "name"
INPUT = "input"
READ = "read"
RELAY = "relay"
RELAYS = "relays_durations"
START_TIME = "start_time"
CFG_TIME_PATTERN = r"(?P<date>\d{2}/\d{2}/\d{4})?\s?(?P<time>\d{2}:\d{2}:\d{2})?\.?(?P<milliseconds>\d{1,6})?"
ALL_RELAYS_OFF = [0] * 8
ALL_RELAYS_ID = [1, 2, 3, 4, 5, 6, 7, 8]
RELAYS_DEFAULT = "relays_default"
HTTP = "http"
DEPENDENCIES = "dependencies"
MAPPING = "dependencies_mapping"
TRIGGERS = "triggers"
AND = "and"
NOT = "not"
STATUS = "status"
TOGGLE_ON_OFF = "toggle_on_off"
SWITCH_ON = "switch_on"
SWITCH_OFF = "switch_off"
BUFFER_SIZE = 1024
LISTENER_SLEEPING_DELAY = 0.5
